## Travis CI configuration for the cookiecutter-cpp-lib project template.
##
##   <https://travis-ci.org/mdklatt/cookiecutter-cpp-lib>
##
language: cpp

compiler:
  - clang
  - gcc

branches:
  only:
    - master
    - dev

sudo: true
dist: trusty  # beta; needed for C++11

before_script:
  # Install Cookiecutter. Because this is a C++ project Travis does not create
  # a Python virtualenv, so pip needs to install locally.
  - pip install --requirement=requirements.txt --user
  
script:
  - python tests/test_template.py
